FROM rust:alpine3.18
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM alpine:3.18
RUN apk add --no-cache mysql-client
ENTRYPOINT ["mysql"]

COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
